- schemas/simple/collections/dataset.json
- schemas/simple/collections/organization.json
- schemas/simple/config.yml
> Adds simple schema definition

- composer.json
- modules/custom/dkan_dataset/dkan_dataset.info.yml
- modules/custom/dkan_dataset/dkan_dataset.module
- modules/custom/json_schema_field/json_schema_field.info.yml
> Group sync functionality

- modules/custom/interra_api/config/pageSchema.yml
- modules/custom/interra_api/src/Controller/ApiController.php
- modules/custom/interra_api/src/Interra.php
- modules/custom/interra_api/src/SiteMap.php
This adds cors for the interra api and fixes a directory issue.
> Fixes directory lookup issue and adds cors

- modules/custom/dkan_api/dkan_api.routing.yml
- modules/custom/dkan_api/src/Controller/Api.php
This PR includes the dkan_api portion of my work for 190, without bringing in Cypress test or fmizzell/sae changes. Let me know if you have any questions or concerns. Thanks in advance.
> Update data via patch api requests

- modules/custom/dkan_harvest/dkan_harvest.install
> Replace varchar with varchar_ascii in dkan_harvest_schema()

- .circleci/config.yml
- config/install/system.action.user_add_role_action.api_user.yml
- config/install/system.action.user_remove_role_action.api_user.yml
- config/install/user.role.api_user.yml
- cypress/integration/api.spec.js
PR for PQDC-567
* Add config for an API User role and permission
* Configure CircleCI to create a test user with API User role
* Add Cypress API tests
> Create api user role

- modules/custom/dkan_api/src/Storage/DrupalNodeDataset.php
- modules/custom/dkan_api/src/Storage/ThemeValueReferencer.php
For PQDC-400
- WIP
- Demo'ed to @fmizzell on 04/23
- Could break other parts of site not expecting themes to be references
> Treat theme values as reference when datasets are created

- modules/custom/dkan_data/dkan_data.module
Keep the values from the JSON source or a manual update.
> Remove the connection of issued and modified values to the drupal node properties

- modules/custom/dkan_data/config/install/dkan_data.settings.yml
> Reference distributions by default

- cypress/integration/api.spec.js
- modules/custom/dkan_data/dkan_data.module
- modules/custom/dkan_data/src/ValueReferencer.php
- modules/custom/dkan_data/tests/src/Unit/ValueReferencerTest.php
> Add different dereferencing methods based on API query parameter

- cypress/integration/sqlendpoint.spec.js
- modules/custom/dkan_data/dkan_data.module
- modules/custom/dkan_datastore/src/Commands/DkanDatastoreCommands.php
- modules/custom/dkan_datastore/src/Manager/DatastoreManagerBuilderHelper.php
- modules/custom/dkan_datastore/tests/src/Unit/Manager/DatastoreManagerBuilderHelperTest.php
> Datastore drush import should handle resources

- modules/custom/dkan_api/dkan_api.routing.yml
- modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml
- modules/custom/dkan_api/src/Controller/Docs.php
Provides frontend's Swagger / OpenAPI with the yml needed to generate the OpenAPI documentation.
> API documentation endpoint

- composer.json
- modules/custom/dkan_api/src/Storage/DrupalNodeDataset.php
- modules/custom/dkan_api/tests/src/Unit/Storage/DrupalNodeDatasetTest.php
There are so many threats and ways to filter them. It seems like HTMLPurifier (19 millions downloads on Packagist) is a nice approach with sensible defaults that removes only potentially dangerous tags while leaving others untouched.
After feedback, I can revisit and then add some unit tests.
> Validate input 762

- cypress/integration/api.spec.js
- dredd/dredd-hooks.js
- modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml
- modules/custom/dkan_harvest/tests/src/Unit/Service/HarvestTest.php
Moved some DKAN API tests from Cypress to Dredd.
Number of tests passing:
Before:
26 Cypress, 10 Dredd
After
18 Cypress, 19 Dredd
1. Check out this branch
1. Run `dktl dkan:test-dredd` and `dktl dkan:test-cypress`
> Clean up integration tests

- modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml
- modules/custom/dkan_datastore/dkan_datastore.routing.yml
- modules/custom/dkan_sql_endpoint/dkan_sql_endpoint.routing.yml
- modules/custom/dkan_sql_endpoint/src/Controller/Api.php
Done:
- Modify paths for datastore and sql endpoints
- Modify sql endpoint so the query is a query parameter rather than a url fragment
To do:
- Determine how to handle the single import "now or deferred"
> Update datastore endpoints

- cypress.json
- cypress/fixtures/electionDistricts.json
- cypress/integration/datastore.spec.js
- cypress/integration/metastore.spec.js
- cypress/integration/sqlendpoint.spec.js
- dkan2.info.yml
- dredd/dredd-hooks.js
- modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml
- Fixes paths in Cypress tests
- Factor out hardcoded values and place them in a fixture or environment variables
> Fix and improve Cypress tests for datastore, sql endpoint and metastore

- modules/custom/dkan_frontend/dkan_frontend.routing.yml
- modules/custom/dkan_frontend/dkan_frontend.services.yml
Update for https://github.com/GetDKAN/dkan2/issues/238
> Changing DKAN frontend routes from a class to service

- docs_assets/pages/4.3_datastore_api.md
**Note:** I only updated the source `.md` file to get the ball rolling. Another developer will need to compile the docs.
> Update SQL Endpoint example URL in docs

- cypress/integration/01_metastore.spec.js
- dredd/dredd-hooks.js
- modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml
- modules/custom/dkan_metastore/src/Exception/CannotChangeUuidException.php
- modules/custom/dkan_metastore/src/Exception/ExistingObjectException.php
- modules/custom/dkan_metastore/src/Exception/InvalidJsonException.php
- modules/custom/dkan_metastore/src/Exception/InvalidPayload.php
- modules/custom/dkan_metastore/src/Exception/MetastoreException.php
- modules/custom/dkan_metastore/src/Exception/MissingObjectException.php
- modules/custom/dkan_metastore/src/Exception/MissingPayloadException.php
- modules/custom/dkan_metastore/src/Exception/ObjectExists.php
- modules/custom/dkan_metastore/src/Exception/ObjectNotFound.php
- modules/custom/dkan_metastore/src/Exception/UnmodifiedObjectException.php
- modules/custom/dkan_metastore/src/Service.php
- modules/custom/dkan_metastore/src/WebServiceApi.php
- modules/custom/dkan_metastore/tests/src/Unit/ServiceTest.php
- modules/custom/dkan_metastore/tests/src/Unit/WebServiceApiTest.php
- Refactoring exceptions to simplify complexity
- Add a new `PUT` response for when object would not be modified
- Additional code coverage
- Update openapi spec and Dredd tests
> Metastore improvements

- modules/custom/dkan_frontend/src/Routing/RouteProvider.php
> Checking the frontend folder exists before looking inside.

- composer.json
- modules/custom/dkan_common/src/Storage/AbstractDatabaseTable.php
- modules/custom/dkan_datastore/src/Service/Import.php
- modules/custom/dkan_datastore/src/Service/ImporterList/ImporterListItem.php
Awaits the merging of PRs of its dependencies:
1. https://github.com/GetDKAN/csv-parser/pull/13 (merged)
1. https://github.com/fmizzell/maquina/pull/5
1. https://github.com/GetDKAN/datastore/pull/22
> Ingestion optimization

- cypress/integration/01_metastore.spec.js
- modules/custom/dkan_metastore/dkan_metastore.routing.yml
- modules/custom/dkan_metastore/src/Service.php
- modules/custom/dkan_metastore/src/WebServiceApi.php
- modules/custom/dkan_metastore/tests/src/Unit/ServiceTest.php
- modules/custom/dkan_metastore/tests/src/Unit/WebServiceApiTest.php
- modules/custom/dkan_schema/src/SchemaRetriever.php
- modules/custom/dkan_schema/tests/src/Unit/SchemaRetrieverTest.php
- schema/collections/catalog.json
- schema/collections/data.json
1. Check out branch, clear cache
1. Visit [http://dkan/data.json](http://dkan/data.json)
1. Verify the json keys, aside from `dataset`, match those within file `schema/collections/catalog.json`
1. The `dataset` key should be an array of all datasets within your Dkan site, similar to a `GET` on `http://dkan/api/1/metastore/schemas/dataset/items`
> Generate data catalog
