GetDKAN/dkan2

- composer.json
- modules/custom/dkan_datastore/dkan_datastore.routing.yml
- modules/custom/dkan_datastore/src/Controller/Datastore.php
- modules/custom/dkan_datastore/src/SqlParser.php
- modules/custom/dkan_datastore/src/Storage/DatastoreQuery.php
* QA *
1. Get a local sandbox of dkan working
2. Bring in the dummy content: `dktl drush dkan-dummy-content:create`
3. Bing a dataset into the datastore: `dktl drush dkan-datastore:import 1f2042ad-c513-4fcf-a933-cae6c6fd35e6`
4. Play with the endpoint
Here is an endpoint calls that should work:
http://dkan/api/v1/sql/[SELECT%20*%20FROM%201f2042ad-c513-4fcf-a933-cae6c6fd35e6][WHERE%20code%20LIKE%20'A%25'%20AND%20tax_rate%20LIKE%20'%25'][ORDER%20BY%20tax_rate,%20name][LIMIT%202%20OFFSET%201];
Any subsets of that query should also work. By a subset I mean that you can remove an brackets block ([...]) from right to left and you should still get results.
The blocks work in order from left to right, so you need the previous block. For example to use an ORDER BY block, you need a WHERE block. …
> Sql Endpoint

- modules/custom/dkan_harvest/src/Load/FileHelper.php
- modules/custom/dkan_harvest/src/Transform/ResourceImporter.php
- modules/custom/dkan_harvest/tests/src/Unit/Transform/ResourceImporterTest.php
#80
`ResourceImporter.php` is a new harvest transform that saves external distribution files locally. This implementation makes the following assumptions:
1. Distribution files should be saved under `public://distribution/[dataset-identifier]/[filename-and-extension]`, where the filename and extension are extracted from the `downloadURL` distribution property.
2. Download URLs should contain a file name and extension in their path (e.g. http://example.com/path/to/file.csv).
Note:
If using this harvest transform via the CLI (e.g. drush), you'll want to configure the `file_public_base_url` in `settings.php` as shown below (otherwise `default` will be used as the host):
```
if (PHP_SAPI == "cli") {
$settings['file_public_base_url'] = "http://dkan/sites/default/files";
}
```
> Harvest transform file importer

- config/install/user.role.administrator.yml
Noticed `dkan2.install` refers to an Administrator role and assigns it to UID 1, though no such role exists. This PR adds it via config.
> Add config for Administrator role

- cypress/integration/api.spec.js
Minor refactor of the Cypress API tests, passes locally and on CI. Feel free to reach out if you have any questions or concerns.
> Refactor Cypress API test by extracting out hard-coded url

- modules/custom/dkan_api/dkan_api.routing.yml
- modules/custom/dkan_api/src/Controller/Docs.php
- modules/custom/dkan_api/tests/src/Unit/Controller/DocsTest.php
* Converts the returned openapi spec to json
* Adds route `api/v1/docs/unauthenticated` to api docs endpoint
> Improve docs endpoint, get api spec of unauthenticated routes

- modules/custom/dkan_api/dkan_api.routing.yml
- modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml
- modules/custom/dkan_api/src/Controller/Docs.php
- modules/custom/dkan_api/tests/src/Unit/Controller/DocsTest.php
Modifies the openapi dkan spec for a specific dataset uuid.
Steps to tests:
1. Check out branch, clear cache
2. Use curl or Postman to `GET` `dkan/api/v1/docs/specific/c9e2d352-e24c-4051-9158-f48127aa5692`
3. Paste the resulting json into [Swagger Editor](https://editor.swagger.io/) (it will ask you to convert json to yaml, do it)
4. Verify the resulting API Docs is specific to this dataset, with two paths: one to get this dataset and one to get a sample result of resource's sql query: ```"paths": {
"/api/v1/dataset/c9e2d352-e24c-4051-9158-f48127aa5692": { ... },
"/api/v1/sql/[SELECT * FROM 36c5bdc2-d60b-410f-8666-07354516ee10];": { ... }
}```
5. If possible, try with other dataset which have resources in the datastore
> Dataset specific api spec

- modules/custom/dkan_harvest/src/Drush/Commands.php
Had a local branch including some corrections / clean-up when I was working on 453. This was stuck in no-builds-land until the recent build fixes.
No new code, just fixed 3 types and applied Drupal coding standards by running the code beautifier and fixer at command line.
> Apply coding standards and fix some typos

- modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml
- Add harvest, datastore and docs endpoints
- Add schema and content details, especially in responses and request payloads
- Use referencing for parameters and schema to reduce repetition
This PR only touches our OpenAPI yams file, so it's entirely documentation rather than code.
> Improve OpenAPI spec with new endpoints, schema and parameter references

- modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml
1. Installed [speccy](https://speccy.io)
1. Ran `speccy lint modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml`
1. Applied all but one of the recommendations.
Remaining item is contact info (name, url, email), which might need a different approach.
No code or logic change, no visual changes to our API docs endpoints.
> Apply speccy.io linting recommendations to our openapi spec

- .circleci/config.yml
CircleCI fails for the same reason it does on master: Two unit tests fail.
I created a `test` branch to test CircleCI with the skipping of the two above tests, to proceed beyond them and test the Circle changes: The result for that test is here: https://circleci.com/gh/GetDKAN/dkan2/742
Expand the integration part of the result, and one can verify that Dredd is passing.
This PR also adds Dredd to CircleCI but without skipping the 2 unit tests.
For that reason I believe it is safe to merge.
Feel free to reach out if you have any questions or concerns.
> Add Dredd tests to CircleCI

- dredd/dredd-hooks.js
- modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml
- modules/custom/dkan_api/src/Routing/RouteProvider.php
Per discussion with @fmizzell, creating or deleting property references does not make sense, as they should created or deleted as a side effect of datasets being modified, not directly.
This removes their documentation and dredd tests.
> Remove openapi and dredd endpoints to create or delete property references

- modules/custom/dkan_datastore/src/Storage/DatabaseTable.php
- modules/custom/dkan_sql_endpoint/config/install/dkan_sql_endpoint.settings.yml
- modules/custom/dkan_sql_endpoint/dkan_sql_endpoint.info.yml
- modules/custom/dkan_sql_endpoint/dkan_sql_endpoint.links.menu.yml
- modules/custom/dkan_sql_endpoint/dkan_sql_endpoint.routing.yml
- modules/custom/dkan_sql_endpoint/src/Controller/Api.php
- modules/custom/dkan_sql_endpoint/src/Form/DkanSqlEndpointSettingsForm.php
- modules/custom/dkan_sql_endpoint/tests/src/Unit/Controller/ApiTest.php
1. Have a site with datasets and at least one datastore
1. Checkout this branch
1. Uninstall and reinstall the DKAN SQL Endpoint module
1. Visit `/admin/config/dkan/sql_endpoint` to verify the default limit number of rows (feel free to set it to something more conducive to manual testing)
1. Run some SQL query on your datastore via our endpoint (feel free to test several queries with their own LIMIT statements)
> Limit number of rows returned from sql endpoint

- modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml
- modules/custom/dkan_api/src/Controller/Api.php
- modules/custom/dkan_api/src/Routing/RouteProvider.php
- modules/custom/dkan_api/tests/src/Unit/Controller/ApiTest.php
- modules/custom/dkan_api/tests/src/Unit/Routing/RouteProviderTest.php
Adds an `api/v1/dataset/{uuid}/resources` endpoint, including:
- Documentation
- Dredd automated testing
- Unit tests
- Refactored dkan_api's routes() to lower code climate code complexity
> Dataset UUID resources endpoint

- cypress/integration/api.spec.js
- cypress/integration/datastore.spec.js
- cypress/integration/sqlendpoint.spec.js
- modules/custom/dkan_api/src/Controller/Api.php
- modules/custom/dkan_api/src/Controller/Docs.php
- modules/custom/dkan_data/dkan_data.module
- modules/custom/dkan_data/src/ValueReferencer.php
- modules/custom/dkan_data/tests/src/Unit/ValueReferencerTest.php
- modules/custom/dkan_datastore/src/Drush/Commands.php
- Rename query parameter `values` to `view`, and its possible values `both|identifier|data` to `verbose|minimal|default` respectively.
- Fix Cypress tests
- Passes Cypress and Dredd tests
Note: A similar PR should address the same changes in the frontend.
> Rename the dereferencing query parameter and its values

- modules/custom/dkan_api/docs/dkan_api_openapi_spec.yml
Updates the DKAN OpenAPI spec to reflect that previous PR #202 locked some harvest endpoints by requiring authentication.
> Update OpenAPI spec for harvest endpoints

- composer.json
- modules/custom/dkan_data/dkan_data.services.yml
- modules/custom/dkan_data/src/Service/Uuid5.php
- modules/custom/dkan_data/src/ValueReferencer.php
- modules/custom/dkan_data/tests/src/Unit/Service/Uuid5Test.php
- modules/custom/dkan_data/tests/src/Unit/ValueReferencerTest.php
One way to test could be to spin up the site twice, and verify that uuid's for references items (themes, keywords, distributions, publishers) remain the same. This can be done by doing the following requests, if testing on the old API:
{code}
http://dkan/api/v1/keyword
http://dkan/api/v1/theme
http://dkan/api/v1/distribution
http://dkan/api/v1/publisher
{code}
If this PR is tested after the API changes made it in master, then:
{code}
http://dkan/api/1/metastore/schemas/keyword/items
http://dkan/api/1/metastore/schemas/theme/items
http://dkan/api/1/metastore/schemas/distribution/items
http://dkan/api/1/metastore/schemas/publisher/items
{code}
> Switch to predictable UUID hashing for property references

- modules/custom/dkan_lunr/dkan_lunr.routing.yml
This PR updates the endpoint used for the frontend searches to match the new format of `api/1/<source>/endpoint` instead of the old `api/v1/endpoint`. This issue came up while testing the frontend against 3.0.0-rc1.
> Update Lunr endpoint with new versioning format

- .circleci/config.yml
- composer.json
Per https://docs.drush.org/en/master/install/, "it is recommended that Drupal sites be built using Composer, with Drush listed as a dependency. ".
> Add drush as drupal dep

- modules/custom/dkan_data/dkan_data.module
- modules/custom/dkan_datastore/src/Drush.php
- modules/custom/dkan_metastore/src/Controller/Api.php
Ran into the following error:
`Error: Undefined class constant 'DEREFERENCE_OUTPUT_VERBOSE' in /var/www/docroot/profiles/contrib/dkan2/modules/custom/dkan_datastore/src/Drush.php`
Which led me to replacing instances of `DEREFERENCE_OUTPUT_VERBOSE`, and even removing a `DEREFERENCE_OUTPUT_MINIMAL`.
> Remove or replace outdated dereferencing methods

- modules/custom/dkan_api/tests/src/Unit/Controller/DocsTest.php
- modules/custom/dkan_api/tests/src/Unit/Controller/docs/dkan_api_openapi_spec.yml
- modules/custom/dkan_metastore/src/WebServiceApiDocs.php
- modules/custom/dkan_metastore/tests/src/Unit/WebServiceApiDocsTest.php
- modules/custom/dkan_metastore/tests/src/Unit/docs/dkan_api_openapi_spec.yml
This replaces a remnant from an older version of the DKAN API.
> Replace outdated api/v1/dataset/{uuid} path in code and unit tests

- modules/custom/dkan_metastore/src/WebServiceApiDocs.php
This PR proposes a refactoring of the WebServiceApiDocs class, where a couple things seemed awkward:
1. Having to know the complete list of paths and operations we did not want. Adding new paths to our API would break the dataset-specific doc or require these new paths to be removed as well, which seemed repetitive. We simplify the logic by flipping it: chose only what to keep, discarding anything else.
1. API paths and operations where treated and removed individually. It removed a verb everywhere, without allowing to keep a verb in one path but not another. Now paths and verbs are treated as a unit to describe one endpoint. More combinations are possible.
> Simplify process to create dataset-specific openapi docs

- modules/custom/dkan_metastore/src/WebServiceApiDocs.php
- modules/custom/dkan_metastore/tests/src/Unit/WebServiceApiDocsTest.php
- modules/custom/dkan_metastore/tests/src/Unit/docs/dkan_api_openapi_spec.yml
PR fixes or improves the following:
1. Dataset-specific docs was mistakenly mentioning the old {{api/v1/sql}} endpoint, as seen here: <img width="930" alt="Screen Shot 2019-11-27 at 8 30 01 PM" src="https://user-images.githubusercontent.com/729791/69777345-bc29c300-1154-11ea-9339-d99bae4a191c.png">
1. Improves unit testing coverage, bumping to 100% in all but one function of class WebServiceApiDocs
> Improve dataset specific docs

- modules/custom/dkan_metastore/tests/src/Unit/ServiceTest.php
Noticed this minor clean up as I'm getting more familiar with new unit test approach.
> Extract common mock chain from dkan_metastore service test

- modules/custom/dkan_dummy_content/files/CDCSmokingRates.csv
1. `dktl install`
1. `dktl drush dkan-dummy-content:create`
1. `dktl drush cron`
The output should include something similar (different UUID generated) to this, aside from the different UUID generated:
```
[error]  Import for ... returned an error: SQLSTATE[42000]:
Syntax error or access violation: 1166
Incorrect column name '': CREATE TABLE 
```
This PR addresses this error, by adding the missing column title in a CSV.
> Missing column title causing sql error during import

- modules/custom/dkan_metastore/src/WebServiceApiDocs.php
- modules/custom/dkan_metastore/tests/src/Unit/WebServiceApiDocsTest.php
- modules/custom/dkan_metastore/tests/src/Unit/docs/dkan_api_openapi_spec.yml
Some refactoring to clean things up and ease hiding the SQL endpoint docs conditionally on plugins (i.e. non-public accessLevel) while maintaining code coverage.
> Refactor web service api docs

- modules/custom/dkan_data/tests/src/Unit/Service/Uuid5Test.php
1. Address the 2 errors below, returned by PHPUnit on our Uuid5 service.
1. Increase test coverage to include Uuid5's `isValid()`.
```
1) Drupal\dkan_data\Tests\Unit\Uuid5Test::testGenerate with data set "string" ('foo', 'bar', 'fd088d96-7c6b-5adf-8581-cbb18a5dad67')
Non-static method Drupal\dkan_data\Service\Uuid5::generate() should not be called statically
/Users/thierry.dallacroce/Code/pqdc/docroot/profiles/contrib/dkan2/modules/custom/dkan_data/tests/src/Unit/Service/Uuid5Test.php:33
2) Drupal\dkan_data\Tests\Unit\Uuid5Test::testGenerate with data set "non-string" ('foo', stdClass Object (...), 'e9de513e-b4d7-5b05-902b-f90ee7a5db52')
Non-static method Drupal\dkan_data\Service\Uuid5::generate() should not be called statically
/Users/thierry.dallacroce/Code/pqdc/docroot/profiles/contrib/ …
```
> Fix error in test of uuid5 service

- modules/custom/dkan_alt_api/dkan_alt_api.info.yml
- modules/custom/dkan_alt_api/dkan_alt_api.permissions.yml
- modules/custom/dkan_alt_api/dkan_alt_api.routing.yml
- Disabled by default
- New permissions, not tied to a role yet
- New endpoint URLs
- Re-uses the existing Metastore and SQL controllers
> Alternate API module

- composer.json
- config/install/views.view.dkan_content.yml
- dkan2.info.yml
- modules/custom/dkan_admin/config/install/views.view.content.yml
- modules/custom/dkan_admin/config/install/views.view.dkan_content.yml
- modules/custom/dkan_admin/dkan_admin.info.yml
- modules/custom/dkan_admin/dkan_admin.module
- Adds vbo module
- Adds admin_toolbar
- Adds new view to override default `admin/content` view
- Adds column for data type
- Adds bulk delete operation
- `drush dkan-dummy-content:create`
- disable default drupal admin/content view
- confirm `admin/content` displays new view with vbo bulk delete op and column for data type
> Add custom node content view

- modules/custom/dkan_admin/dkan_admin.module
Visiting the Recent logs messages view caused the following error:
`Error: Call to a member function id() on null in dkan_admin_preprocess_views_view_field() (line 40 of /var/www/docroot/profiles/contrib/dkan2/modules/custom/dkan_admin/dkan_admin.module)`
Which I tracked it down to code which this PR moves into the conditional.
> Not all views display entities

- modules/custom/dkan_search/src/ComplexData/Dataset.php
- modules/custom/dkan_search/src/WebServiceApi.php
- modules/custom/dkan_search/tests/src/Unit/ComplexData/DatasetTest.php
- modules/custom/dkan_search/tests/src/Unit/WebServiceApi2Test.php
- schema/collections/dataset.json
This branch should work with https://github.com/GetDKAN/data-catalog-frontend/pull/16
Related ticket: https://github.com/getdkan/dkan2/issues/344
1. Confirm you can add additional schema fields like publisher.name and distribution.title to the search index `/admin/config/search/search-api/index/dkan/fields`
> Add additional field options for indexing

- modules/custom/dkan_datastore/src/Drush.php
Noticed the following error while running `drush dkan-datastore:drop <UUID>`:
```
[error]  Error: Class 'Drupal\dkan_datastore\ValueReferencer' not found in
Drupal\dkan_datastore\Drush->drop() (line 139 of
docroot/profiles/contrib/dkan2/modules/custom/dkan_datastore/src/Drush.php)
#0 [internal function]: Drupal\dkan_datastore\Drush->drop('<UUID>', Array)
```
This PR should address the issue
> Fix missing class name

- .circleci/config.yml
Use master branch of dkan-tools. I forgot to remove the adjustment after QA on #373 🤦
> Restore circleci step for installing dkan-tools

- schema/collections/dataset.json
There are accessibility issues on the dkan_metadata_form, according to the standard WCAG AA:
```
This textinput element does not have a name available to an accessibility API. Valid names are: label element, title undefined, aria-label undefined, aria-labelledby undefined.
```
That is happening for every textfield on the Category (theme) and Tags (keyword) array fields.
Looking into the code for the rjsf project, we discovered the issue is actually in the schema we are using, so here I'm updating the schema so we comply with the WCAG AA standard.
This new schema can be tested in the rjsf playground here https://rjsf-team.github.io/react-jsonschema-form/, add this schema and run the HTML Codesniffer tool, you'll see that the error described above is not present anymore for any field in the …
> Update schema to include title for Theme and Keywords array items.

- modules/dkan_metadata_form/src/Drush.php
Running `dktl drush dkan-metadata-form:sync` produced the following error:
```
[error]  TypeError: Argument 1 passed to Masterminds\HTML5::parse() must be an instance of Masterminds\HTML5\Parser\InputStream, string given, called in /var/www/docroot/modules/contrib/dkan2/modules/dkan_metadata_form/src/Drush.php on line 159 in Masterminds\HTML5->parse() (line 166 of /var/www/vendor/masterminds/html5/src/HTML5.php) #0 /var/www/docroot/modules/contrib/dkan2/modules/dkan_metadata_form/src/Drush.php(159): Masterminds\HTML5->parse('<!doctype html>...')
```
I'm fixing that here.
> Pass right variable to HTML5:parse().
